export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
  git
  zsh-autosuggestions
  zsh-nvm
  tmux
)

source $ZSH/oh-my-zsh.sh

#########################
#### USER CONFIGURATION
#########################

# Disable matching
# More info: https://github.com/ohmyzsh/ohmyzsh/issues/31#issuecomment-359728582
unsetopt nomatch

# Setting for zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=244'
bindkey '`' autosuggest-accept

# Settings for ripgrep
[ -f $HOME/.ripgreprc ] && export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc

# Settings for fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden'
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export LANG="en_US.UTF-8"

# Homebrew
export PATH="$PATH:/usr/local/sbin:$HOME/.local/bin"

# Editor
alias vim="nvim"
alias vi="nvim"
export EDITOR='nvim'

# Bind Alt + Arrow to jump word in terminal
bindkey "\e\eOD" backward-word
bindkey "\e\eOC" forward-word

# ZSH aliases
alias zshconfig="vi $HOME/.zshrc"
alias zshreload="source $HOME/.zshrc"

# TMUX aliases
alias tmuxconfig="vi $HOME/.tmux.conf"

# VIM
export VIMCONFIG="$HOME/.config/nvim/init.vim"
export VIMCONFIG_DIR="$HOME/.config/nvim"
alias viconfig="cd $VIMCONFIG_DIR && vi init.vim"

# Utils
# Clear screen but keep buffer
alias cl="clear"
# Clear screen AND buffer: source https://unix.stackexchange.com/a/531178
alias clb="printf '\ec\e[3J'"
# Ignore man errors on macOS Catalina
alias man="man 2>/dev/null"

# ShopBack
[ -f $HOME/.shopback.zsh ] && source $HOME/.shopback.zsh
