export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
  git
  zsh-autosuggestions
  zsh-nvm
)

source $ZSH/oh-my-zsh.sh

#########################
#### USER CONFIGURATION
#########################

# Setting for zsh-autosuggestions

# If using paper-color DARK theme
# ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=235'

# If using paper-color LIGHT theme
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=244'
bindkey '`' autosuggest-accept

# Settings for fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden --sortr=accessed'
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export LANG="en_US.UTF-8"

# Support homebrew
export PATH="$PATH:/usr/local/sbin:$HOME/.local/bin"

# Editor
alias vim="nvim"
alias vi="nvim"
export EDITOR='nvim'

# Bind Alt + Arrow to jump word in terminal
bindkey "\e\eOD" backward-word
bindkey "\e\eOC" forward-word

# ZSH aliases
alias zshconfig="vi $HOME/.zshrc"
alias zshreload="source $HOME/.zshrc"

# TMUX aliases
alias tmuxconfig="vi $HOME/.tmux.conf"
alias tmuxns="tmux new -s $USER"
alias tmuxat="tmux attach -t $USER"

# VIM
export VIMCONFIG="$HOME/.config/nvim/init.vim"
export VIMCONFIG_DIR="$HOME/.config/nvim"
alias viconfig="cd $VIMCONFIG_DIR && vi init.vim"

# Utils
alias cl="clear"
